In [1]:
from funcoesTermosol import importa, plota, geraSaida
import numpy as np

[nn,N,nm,Inc,nc,F,nr,R, L, angle] = importa('entrada.xlsx')
print(nm)
geraSaida('teste',F,F,F,F,F)

3


In [2]:
# c**2      cs      -c**2   -cs
# cs        s**2    -cs     -s**2
# -c**2     -cs     c**2    cs
# -cs       -s**2   cs      s**2

E = Inc[0,2]
A = Inc[0,3]
L = Inc[0,0]
theta = angle[0,0]
K1 = np.zeros((4,4))

K1[0,0] = (E*A/L)*np.cos(theta)**2
K1[0,1] = (E*A/L)*np.cos(theta)*np.sin(theta)
K1[0,2] = -(E*A/L)*np.cos(theta)**2
K1[0,3] = -(E*A/L)*np.cos(theta)*np.sin(theta)

K1[1,0] = (E*A/L)*np.cos(theta)*np.sin(theta)
K1[1,1] = (E*A/L)*np.sin(theta)**2
K1[1,2] = -(E*A/L)*np.cos(theta)*np.sin(theta)
K1[1,3] = -(E*A/L)*np.sin(theta)**2

K1[2,0] = -(E*A/L)*np.cos(theta)**2
K1[2,1] = -(E*A/L)*np.cos(theta)*np.sin(theta)
K1[2,2] = (E*A/L)*np.cos(theta)**2
K1[2,3] = (E*A/L)*np.cos(theta)*np.sin(theta)

K1[3,0] = -(E*A/L)*np.cos(theta)*np.sin(theta)
K1[3,1] = -(E*A/L)*np.sin(theta)**2
K1[3,2] = (E*A/L)*np.cos(theta)*np.sin(theta)
K1[3,3] = (E*A/L)*np.sin(theta)**2

print (K1)

[[ 1.57474777e-25  2.57175828e-09 -1.57474777e-25 -2.57175828e-09]
 [ 2.57175828e-09  4.20000000e+07 -2.57175828e-09 -4.20000000e+07]
 [-1.57474777e-25 -2.57175828e-09  1.57474777e-25  2.57175828e-09]
 [-2.57175828e-09 -4.20000000e+07  2.57175828e-09  4.20000000e+07]]
