In [1]:
from funcoesTermosol import importa, plota, geraSaida
import numpy as np

[nn,N,nm,Inc,nc,F,nr,R, L, angle] = importa('entrada.xlsx')
print(R)
geraSaida('teste',F,F,F,F,F)

[[1.0e+00 2.0e+00 2.1e+11 2.0e-04]
 [2.0e+00 3.0e+00 2.1e+11 2.0e-04]
 [3.0e+00 1.0e+00 2.1e+11 2.0e-04]]
[[1. 1.]
 [2. 1.]
 [2. 2.]]


In [16]:
# Define a matriz de rigidez local para cada barra
K = []
nos = np.zeros((nm,2))

for i in range(nm):
    E = Inc[i,2]
    A = Inc[i,3]
    L = Inc[i,0]
    theta = angle[i,0]

    nos[i,0] = Inc[i,0]
    nos[i,1] = Inc[i,1]

    K1 = np.zeros((4,4))

    K1[0,0] = (E*A/L)*np.cos(theta)**2
    K1[0,1] = (E*A/L)*np.cos(theta)*np.sin(theta)
    K1[0,2] = -(E*A/L)*np.cos(theta)**2
    K1[0,3] = -(E*A/L)*np.cos(theta)*np.sin(theta)

    K1[1,0] = (E*A/L)*np.cos(theta)*np.sin(theta)
    K1[1,1] = (E*A/L)*np.sin(theta)**2
    K1[1,2] = -(E*A/L)*np.cos(theta)*np.sin(theta)
    K1[1,3] = -(E*A/L)*np.sin(theta)**2

    K1[2,0] = -(E*A/L)*np.cos(theta)**2
    K1[2,1] = -(E*A/L)*np.cos(theta)*np.sin(theta)
    K1[2,2] = (E*A/L)*np.cos(theta)**2
    K1[2,3] = (E*A/L)*np.cos(theta)*np.sin(theta)

    K1[3,0] = -(E*A/L)*np.cos(theta)*np.sin(theta)
    K1[3,1] = -(E*A/L)*np.sin(theta)**2
    K1[3,2] = (E*A/L)*np.cos(theta)*np.sin(theta)
    K1[3,3] = (E*A/L)*np.sin(theta)**2
    K.append(K1)

# if a number in K is between -1e-8 and 1e-8, it is considered 0
for i in range(nm):
    for j in range(4):
        for k in range(4):
            if K[i][j,k] < 1e-8 and K[i][j,k] > -1e-8:
                K[i][j,k] = 0


# Define a matriz global de rigidez
KG = np.zeros((nn*2,nn*2))
print(F)

for count, matrizLocal in enumerate(K):
    n = nos[count]
    m1 = int(n[0])
    m2 = int(n[1])
    KG[np.ix_([(m1 - 1)*2, (m1 - 1)*2+1, (m2 - 1)*2, (m2 - 1)*2+1], [(m1 - 1)*2, (m1 - 1)*2+1, (m2 - 1)*2, (m2 - 1)*2+1])] += matrizLocal[0:4,0:4]

for r in R:
    KG[int(r[0]-1)*2  + (int(r[1]) - 1), :] = 0
    KG[:, int(r[0]-1)*2  + (int(r[1]) - 1)] = 0

print(KG)

fglobal = F.copy()

[[   0.]
 [   0.]
 [   0.]
 [   0.]
 [ 150.]
 [-100.]]
[[  5040000.   6720000.         0.         0.  -5040000.  -6720000.]
 [  6720000.  50960000.         0. -42000000.  -6720000.  -8960000.]
 [        0.         0.  21000000.         0. -21000000.         0.]
 [        0. -42000000.         0.  42000000.         0.         0.]
 [ -5040000.  -6720000. -21000000.         0.  26040000.   6720000.]
 [ -6720000.  -8960000.         0.         0.   6720000.   8960000.]]
[[       0.        0.        0.        0.        0.        0.]
 [       0. 50960000.        0.        0. -6720000. -8960000.]
 [       0.        0.        0.        0.        0.        0.]
 [       0.        0.        0.        0.        0.        0.]
 [       0. -6720000.        0.        0. 26040000.  6720000.]
 [       0. -8960000.        0.        0.  6720000.  8960000.]]
